version: '2'
services:
  headless-client:
    environment: &environment
      # need your own TOKEN_APP_SEED for testing, generate it at https://www.tokenbrowser.com/token-seed-generator/
      # your dev seed
      - TOKEN_APP_SEED=follow chalk drift dice ancient frost make material isolate creek open seven
      # your dev user name
      - TOKEN_APP_USERNAME=ico_dev_foreseaz
      # your dev app name
      - TOKEN_APP_NAME=ico_dev_foreseaz
      - TOKEN_APP_AVATAR=attachments/eth_ico.png
      - REDIS_URL=redis://h:rlcMWNrxXgqS0xM8aWCYuE0R@redis:6379
      - DATABASE_URL=postgres://token:va5uOdJBqu2dZ1@postgres:5432/token
      - LOG_LEVEL=INFO
      - ENABLE_LOG_TIMESTAMPS=0
